services:
  db:
    container_name: morangofarm
    image: postgres:alpine
    environment:
      POSTGRES_USER: godoi
      POSTGRES_PASSWORD: password
      PGDATA: /data/morangofarm
    volumes:
      - db:/data/morangofarm
    ports:
      - "5333:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: